version: '3.8'

services:
  restapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # restart: always
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    networks:
      - net
  db:
    image: postgres:17.0
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=safeguard
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
  

  chromadb:
    build:
      context: ./ml/chromadb/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - net
    volumes:
      - chromadb-data:/data

  clip:
    build:
      context: ./ml/clip
      dockerfile: Dockerfile
    networks:
      - net
    runtime: nvidia
    environment:
      - POLLING_URL=http://restapi:8000/api/v1/image/poll/
      - CHROMADB_URL=http://chromadb:8001
    depends_on:
      - restapi
      - chromadb

  face:
    build:
      context: ./ml/face
      dockerfile: Dockerfile
    networks:
      - net
    environment:
      - POLLING_URL=http://restapi:8000/api/v1/image/poll
      - CHROMADB_URL=http://chromadb:8001
    depends_on:
      - restapi
      - chromadb
    
networks:
  net:
    driver: bridge

volumes:
  db-data:
  chromadb-data:

