# Generated by Django 5.1.3 on 2024-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('embedding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='check_images/')),
                ('image', models.ManyToManyField(to='app.image')),
            ],
        ),
    ]
